### ISSUE TITLE
[Bug] I can't download poopscript on Visual Basic

### ISSUE THREAD

**Issue by FreeBSoD** [GoldenretriverYT/PoopScript#1]
**Describe the bug**
I can't download poopscript on Visual Basic

**How to reproduce**
paste BoobScript code into vb script

**Expected behavior**
Able to use PoopScript

**Please tell me more**
 - What browser are you using? Google but why is this needed? corrpt downloasd?
 - What version of PoopScript are you using? Newest

**Comment by FreeBSoD** [comment]
forgot to tell, i use vs 2019

**Comment by GoldenretriverYT** [comment]
Hello,
PoopScript is run by using the interpreter written in JavaScript. You can't run it in Visual Basic.

**Comment by FreeBSoD** [comment]
@GoldenretriverYT areyou stupid? its a progaming language it should work in visual studio or visual basic whatver is called

**Comment by GoldenretriverYT** [comment]
No. PoopScript is not supported by Visual Studio. PoopScript is simply a interpreted (and bad) language. If you want, you can write an interpreter in Visual Basic yourself.
